import { createServer as nodeCreateServer } from 'node:http';

const html = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GitHub 项目整理</title><style>
:root{font-family:system-ui,-apple-system,sans-serif;color:#1f2937;background:#f6f8fb}body{margin:0}.shell{max-width:1280px;margin:auto;padding:24px}.toolbar,.filters{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.filters{margin-top:14px}.badge,.signal{padding:4px 9px;border-radius:999px;background:#e5e7eb;font-size:13px}.badge.ok{background:#dcfce7;color:#166534}.badge.bad{background:#fee2e2;color:#991b1b}.signal{display:inline-block;margin:2px;background:#fff7ed;color:#9a3412}button{border:0;border-radius:6px;padding:9px 14px;background:#2563eb;color:white;cursor:pointer}button.secondary{background:#64748b}button:disabled{opacity:.5;cursor:not-allowed}input,select{padding:8px;border:1px solid #cbd5e1;border-radius:6px}.notice{margin:16px 0;padding:14px;border:1px solid #f59e0b;background:#fffbeb;border-radius:8px}.workspace{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:18px;margin-top:20px}.panel{background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:14px;overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:10px 8px;border-bottom:1px solid #eef0f3;text-align:left;vertical-align:top}tr.selected{background:#eff6ff}.muted{color:#6b7280}.error{color:#b91c1c}.progress{height:8px;background:#e5e7eb;border-radius:5px;overflow:hidden;margin-top:12px}.progress i{display:block;height:100%;background:#2563eb;width:0}.field{display:inline-flex;align-items:center;gap:4px}.field input{width:55px}@media(max-width:800px){.workspace{grid-template-columns:1fr}.details{order:-1}}
</style></head><body><main class="shell"><h1>GitHub 项目整理</h1>
<div class="toolbar"><span id="auth" class="badge">检查 gh 状态中…</span><button id="scan">开始扫描</button><button id="preview" class="secondary">批量预览</button><button id="confirmUnstar" class="secondary" disabled>确认取消 Star</button><button id="confirmKeep" class="secondary" disabled>确认保留当前关系</button><span id="summary" class="muted"></span></div><div id="notice"></div>
<div class="filters"><input id="search" placeholder="搜索 owner/repo" aria-label="搜索 owner/repo"><select id="signal"><option value="">全部健康信号</option><option value="archived">已归档</option><option value="disabled">已禁用</option><option value="deprecated">deprecated</option><option value="no-recent-commit">无近期提交</option><option value="no-recent-release">无近期 Release</option><option value="no-recent-activity">无近期 Issue/PR 活动</option></select><select id="relation"><option value="">全部关系</option><option value="starred">Star</option><option value="owned">Owned</option><option value="fork">Fork</option></select><select id="listFilter" aria-label="Lists 筛选"><option value="">全部 Lists（扩展入口）</option></select><label><input type="radio" name="view" value="health" checked> 仅健康信号</label><label><input type="radio" name="view" value="all"> 全部项目</label><span class="field">Commit <input id="commitMonths" type="number" min="0" value="12"></span><span class="field">Release <input id="releaseMonths" type="number" min="0" value="18"></span><span class="field">活动 <input id="activityMonths" type="number" min="0" value="6"></span><button id="recalc" class="secondary">重新计算</button></div>
<div class="progress"><i id="bar"></i></div><div class="workspace"><section class="panel"><table><thead><tr><th>选择</th><th>项目条目</th><th>关系</th><th>最近 commit</th><th>Lists</th><th>健康信号</th><th>动作</th></tr></thead><tbody id="rows"><tr><td colspan="7" class="muted">尚未扫描。点击“开始扫描”读取项目条目。</td></tr></tbody></table></section><aside class="panel details"><h2>详情</h2><p id="detail" class="muted">选择表格中的项目查看完整证据与整理建议。</p></aside></div></main><script>
const $=id=>document.getElementById(id);let data=null,selected=null;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function filtered(){const q=$('search').value.trim().toLowerCase(),sig=$('signal').value,rel=$('relation').value,list=$('listFilter').value,all=document.querySelector('input[name=view]:checked')?.value==='all';return (data?.items||[]).filter(i=>(all||i.healthSignals?.length)&&(!q||i.fullName.toLowerCase().includes(q))&&(!sig||i.healthSignals?.some(s=>s.code===sig))&&(!rel||i.relation?.[rel])&&(!list||i.lists?.includes(list)));}
function renderDetail(){const i=(data?.items||[]).find(x=>x.fullName===selected);if(!i){$('detail').innerHTML='<p class="muted">选择表格中的项目查看完整证据与整理建议。</p>';return;}const e=i.evidence||{};$('detail').innerHTML='<h3>'+esc(i.fullName)+'</h3><p>优先级：<strong>'+esc(i.recommendation?.priority||i.priority)+'</strong></p><p>'+esc(i.recommendation?.summary||'')+'</p><h4>扫描证据</h4><ul><li>archived：'+esc(e.status?.archived?'是':'否')+'</li><li>disabled：'+esc(e.status?.disabled?'是':'否')+'</li><li>deprecated：'+esc(e.status?.deprecated?'是':'否')+'</li><li>最近 commit：'+esc(e.latestCommitAt||'无记录')+'</li><li>最近 release：'+esc(e.latestReleaseAt||'无记录')+'</li><li>最近 Issue/PR 活动：'+esc(e.latestActivityAt||'无记录')+'</li></ul><p>命中原因：'+esc((i.recommendation?.reasons||[]).join('、')||'暂无')+'</p><p class="muted">建议仅供确认，archived/deprecated 不会自动执行写操作。</p>';}
function selectedActions(){return [...document.querySelectorAll('input[data-action]:checked')].map(x=>({fullName:x.dataset.name,action:$(x.dataset.action).value}));}
function render(){if(!data)return;const a=data.auth||{};$('auth').textContent=a.state==='authenticated'?'gh 已认证':a.state==='not-installed'?'gh 未安装':a.state==='not-logged-in'?'gh 未登录':'认证不可用';$('auth').className='badge '+(a.state==='authenticated'?'ok':'bad');$('scan').disabled=a.state!=='authenticated';$('preview').disabled=a.state!=='authenticated';if(data.summary)$('summary').textContent='成功 '+data.summary.success+' · 失败 '+data.summary.failed;if(data.progress)$('bar').style.width=(data.progress.percent||0)+'%';const lists=[...new Set((data.items||[]).flatMap(i=>i.lists||[]))],current=$('listFilter').value;$('listFilter').innerHTML='<option value="">全部 Lists（扩展入口）</option>'+lists.map(l=>'<option value="'+esc(l)+'">'+esc(l)+'</option>').join('');$('listFilter').value=lists.includes(current)?current:'';$('rows').innerHTML=filtered().map(i=>'<tr data-name="'+esc(i.fullName)+'" class="'+(selected===i.fullName?'selected':'')+'"><td><input type="checkbox" data-name="'+esc(i.fullName)+'" data-action="act-'+esc(i.id)+'" aria-label="选择 '+esc(i.fullName)+'"></td><td><a href="'+esc(i.url)+'" target="_blank" rel="noreferrer">'+esc(i.fullName)+'</a></td><td>'+esc([i.relation?.starred&&'Star',i.relation?.owned&&'Owned',i.relation?.fork&&'Fork'].filter(Boolean).join(' · ')||'—')+'</td><td>'+esc(i.latestCommitAt||'无记录')+'</td><td>'+esc((i.lists||[]).join('、')||'—')+'</td><td>'+((i.healthSignals||[]).map(s=>'<span class="signal">'+esc(s.label)+'</span>').join('')||'<span class="muted">暂无信号</span>')+'</td><td><select id="act-'+esc(i.id)+'" aria-label="选择 '+esc(i.fullName)+' 的动作"><option value="unstar">取消 Star</option><option value="keep">保留当前关系</option></select></td></tr>').join('')||'<tr><td colspan="7" class="muted">没有符合当前筛选条件的项目条目。</td></tr>';$('rows').querySelectorAll('tr[data-name]').forEach(r=>r.onclick=e=>{if(e.target.matches('input,select'))return;selected=r.dataset.name;render()});renderDetail();}
async function init(){const [s,l]=await Promise.all([fetch('/api/status'),fetch('/api/scan')]);data=await l.json();data.auth=await s.json();const t=data.thresholds||{};if(t.noCommitMonths!=null)$('commitMonths').value=t.noCommitMonths;if(t.noReleaseMonths!=null)$('releaseMonths').value=t.noReleaseMonths;if(t.noActivityMonths!=null)$('activityMonths').value=t.noActivityMonths;render()}$('scan').onclick=async()=>{ $('scan').disabled=true; $('bar').style.width='5%';try{const r=await fetch('/api/scan',{method:'POST'});data=await r.json();render()}finally{$('scan').disabled=false}};$('recalc').onclick=async()=>{const body={noCommitMonths:Number($('commitMonths').value),noReleaseMonths:Number($('releaseMonths').value),noActivityMonths:Number($('activityMonths').value)};const r=await fetch('/api/recalculate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(r.ok){data=await r.json();render()}};['search','signal','relation','listFilter'].forEach(id=>$(id).oninput=render);document.querySelectorAll('input[name=view]').forEach(x=>x.onchange=render);init().catch(e=>$('notice').innerHTML='<div class="notice error">'+esc(e.message)+'</div>');
async function actionRequest(path, body){const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw new Error(value.error||'动作请求失败');return value;}
async function makePreview(){try{preview=await actionRequest('/api/actions/preview',{selections:selectedActions()});if(preview.status==='no-scan')throw new Error('暂无扫描结果');$('notice').innerHTML='<div class="notice"><strong>批量预览</strong><p>取消 Star（'+preview.groups.unstar.length+'）：'+esc(preview.groups.unstar.map(x=>x.fullName).join('、')||'无')+'</p><p>保留当前关系（'+preview.groups.keep.length+'）：'+esc(preview.groups.keep.map(x=>x.fullName).join('、')||'无')+'</p><p>请分别确认，筛选不会自动执行动作。</p></div>';$('confirmUnstar').disabled=!preview.groups.unstar.length;$('confirmKeep').disabled=!preview.groups.keep.length;}catch(e){$('notice').innerHTML='<div class="notice error">'+esc(e.message)+'</div>';}}
async function confirmGroup(action){if(!preview)return;const group=preview.groups[action]||[];if(!group.length)return;try{const result=await actionRequest('/api/actions/confirm',{previewId:preview.id,actions:group});$('notice').innerHTML='<div class="notice">已执行 '+esc(action)+'：成功 '+result.summary.success+'，失败 '+result.summary.failed+'。'+result.results.map(x=>x.status==='failed'?'<p class="error">'+esc(x.fullName)+'：'+esc(x.reason)+' <button data-retry="'+esc(x.fullName)+'">重试</button></p>':x.action==='unstar'?'<p>'+esc(x.fullName)+'：成功 <button data-undo="'+esc(x.fullName)+'">撤销</button></p>':'<p>'+esc(x.fullName)+'：已保留</p>').join('')+'</div>';document.querySelectorAll('[data-undo]').forEach(button=>button.onclick=()=>undoAction(button.dataset.undo));document.querySelectorAll('[data-retry]').forEach(button=>button.onclick=()=>retryAction(button.dataset.retry));preview.groups[action]=[];$('confirmUnstar').disabled=!preview.groups.unstar.length;$('confirmKeep').disabled=!preview.groups.keep.length;if(!preview.groups.unstar.length&&!preview.groups.keep.length)preview=null;}catch(e){$('notice').innerHTML='<div class="notice error">'+esc(e.message)+'</div>';}}
async function retryAction(fullName){const result=await actionRequest('/api/actions/retry',{fullName});$('notice').textContent='重试 '+fullName+'：'+(result.results?.[0]?.status||result.status);}
async function undoAction(fullName){const result=await actionRequest('/api/actions/undo',{fullName});$('notice').textContent='撤销 '+fullName+'：'+(result.reason||result.status);}
$('preview').onclick=makePreview;$('confirmUnstar').onclick=()=>confirmGroup('unstar');$('confirmKeep').onclick=()=>confirmGroup('keep');
</script></body></html>`;

export function createServer({ orchestrator }) {
  return nodeCreateServer(async (req, res) => {
    try {
      if (req.method === 'GET' && req.url === '/') { res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }); return res.end(html); }
      if (req.method === 'GET' && req.url === '/api/status') return json(res, await orchestrator.authStatus());
      if (req.method === 'GET' && req.url === '/api/scan') return json(res, await orchestrator.loadLastScan() || { items: [], failures: [], summary: { total: 0, success: 0, failed: 0 }, progress: { completed: 0, total: 0, percent: 0 } });
      if (req.method === 'GET' && req.url === '/api/progress') return json(res, orchestrator.getProgress?.() || { completed: 0, total: 0, percent: 0, phase: 'idle' });
      if (req.method === 'POST' && req.url === '/api/scan') { const value = await orchestrator.scan({ onProgress: () => {} }); return json(res, value, value.status === 'blocked' ? 403 : 200); }
      if (req.method === 'POST' && req.url === '/api/recalculate') { const value = await orchestrator.recalculate(await readJson(req)); return json(res, value || { error: '暂无扫描结果' }, value ? 200 : 400); }
      if (req.method === 'POST' && req.url === '/api/actions/preview') { if (typeof orchestrator.previewActions !== 'function') return json(res, { error: '当前版本不支持批量动作' }, 400); return json(res, await orchestrator.previewActions(await readJson(req))); }
      if (req.method === 'POST' && req.url === '/api/actions/confirm') { if (typeof orchestrator.confirmActions !== 'function') return json(res, { error: '当前版本不支持批量动作' }, 400); return json(res, await orchestrator.confirmActions(await readJson(req))); }
      if (req.method === 'POST' && req.url === '/api/actions/retry') { if (typeof orchestrator.retryAction !== 'function') return json(res, { error: '当前版本不支持动作重试' }, 400); return json(res, await orchestrator.retryAction(await readJson(req))); }
      if (req.method === 'POST' && req.url === '/api/actions/undo') { if (typeof orchestrator.undoStar !== 'function') return json(res, { error: '当前版本不支持撤销' }, 400); return json(res, await orchestrator.undoStar(await readJson(req))); }
      res.writeHead(404); res.end('Not found');
    } catch (error) { json(res, { error: error.message }, 500); }
  });
}
function json(res, value, status = 200) { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8' }); res.end(JSON.stringify(value)); }
function readJson(req) { return new Promise((resolve, reject) => { let raw = ''; req.on('data', chunk => { raw += chunk; if (raw.length > 1e6) reject(new Error('请求体过大')); }); req.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch (error) { reject(error); } }); req.on('error', reject); }); }
export { html };
