import { createServer as nodeCreateServer } from 'node:http';

const html = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GitHub 项目整理</title><style>
:root{font-family:system-ui,-apple-system,sans-serif;color:#1f2937;background:#f6f8fb}body{margin:0}.shell{max-width:1200px;margin:auto;padding:24px}.toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.badge{padding:5px 10px;border-radius:999px;background:#e5e7eb;font-size:13px}.badge.ok{background:#dcfce7;color:#166534}.badge.bad{background:#fee2e2;color:#991b1b}button{border:0;border-radius:6px;padding:9px 14px;background:#2563eb;color:white;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}.notice{margin:16px 0;padding:14px;border:1px solid #f59e0b;background:#fffbeb;border-radius:8px}.workspace{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:18px;margin-top:20px}.panel{background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:14px;overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:10px 8px;border-bottom:1px solid #eef0f3;text-align:left;white-space:nowrap}.muted{color:#6b7280}.error{color:#b91c1c}.progress{height:8px;background:#e5e7eb;border-radius:5px;overflow:hidden}.progress i{display:block;height:100%;background:#2563eb;width:0}@media(max-width:800px){.workspace{grid-template-columns:1fr}.details{order:-1}}
</style></head><body><main class="shell"><h1>GitHub 项目整理</h1><div class="toolbar"><span id="auth" class="badge">检查 gh 状态中…</span><button id="scan">开始扫描</button><span id="summary" class="muted"></span></div><div id="notice"></div><div class="progress"><i id="bar"></i></div><div class="workspace"><section class="panel"><table><thead><tr><th>项目条目</th><th>关系</th><th>仓库标识</th><th>健康信号</th></tr></thead><tbody id="rows"><tr><td colspan="4" class="muted">尚未扫描。点击“开始扫描”读取已 Star 项目。</td></tr></tbody></table></section><aside class="panel details"><h2>详情</h2><p id="detail" class="muted">选择表格中的项目查看证据。</p></aside></div></main><script>
const $=id=>document.getElementById(id);let data=null;
function render(){if(!data)return; const a=data.auth||{}; $('auth').textContent=a.state==='authenticated'?'gh 已认证':a.state==='not-installed'?'gh 未安装':a.state==='not-logged-in'?'gh 未登录':'认证不可用';$('auth').className='badge '+(a.state==='authenticated'?'ok':'bad');$('scan').disabled=a.state!=='authenticated';$('notice').innerHTML=a.state==='authenticated'?'':'<div class="notice">'+(a.message||'请检查 GitHub CLI 安装和登录状态')+'</div>';if(data.summary)$('summary').textContent='成功 '+data.summary.success+' · 失败 '+data.summary.failed; if(data.progress)$('bar').style.width=(data.progress.percent||0)+'%';if(!data.items)return;$('rows').innerHTML=data.items.map((i,n)=>'<tr data-i="'+n+'"><td><a href="'+i.url+'" target="_blank" rel="noreferrer">'+i.fullName+'</a></td><td>'+(i.relation.starred?'Star ':'')+(i.relation.owned?'Owned ':'')+(i.relation.fork?'Fork':'')+'</td><td>'+i.id+'</td><td>'+((i.healthSignals||[]).map(e=>e.label).join('、')||'暂无信号')+'</td></tr>').join('')+(data.failures||[]).map(f=>'<tr><td colspan="4" class="error">失败（'+f.source+'）：'+f.reason+'</td></tr>').join('');document.querySelectorAll('tr[data-i]').forEach(r=>r.onclick=()=>{const i=data.items[r.dataset.i];$('detail').innerHTML='<strong>'+i.fullName+'</strong><p>最近提交：'+(i.latestCommitAt||'未知')+'</p><p>证据：'+((i.healthSignals||[]).map(e=>e.label).join('、')||'暂无')+'</p>'});}
async function init(){const [s,l]=await Promise.all([fetch('/api/status'),fetch('/api/scan')]);data=await l.json();data.auth=await s.json();render()}$('scan').onclick=async()=>{ $('scan').disabled=true; $('bar').style.width='5%'; const poll=setInterval(async()=>{try{const p=await (await fetch('/api/progress')).json();$('bar').style.width=(p.percent||5)+'%'}catch{}},250); try{const r=await fetch('/api/scan',{method:'POST'});data=await r.json();render()}finally{clearInterval(poll)}};init().catch(e=>$('notice').innerHTML='<div class="notice error">'+e.message+'</div>');
</script></body></html>`;

export function createServer({ orchestrator }) {
  return nodeCreateServer(async (req, res) => {
    try {
      if (req.method === 'GET' && req.url === '/') { res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' }); return res.end(html); }
      if (req.method === 'GET' && req.url === '/api/status') { const value = await orchestrator.authStatus(); return json(res, value); }
      if (req.method === 'GET' && req.url === '/api/scan') { const value = await orchestrator.loadLastScan(); return json(res, value || { items: [], failures: [], summary: { total: 0, success: 0, failed: 0 }, progress: { completed: 0, total: 0, percent: 0 } }); }
      if (req.method === 'GET' && req.url === '/api/progress') { return json(res, orchestrator.getProgress?.() || { completed: 0, total: 0, percent: 0, phase: 'idle' }); }
      if (req.method === 'POST' && req.url === '/api/scan') { const value = await orchestrator.scan({ onProgress: () => {} }); return json(res, value, value.status === 'blocked' ? 403 : 200); }
      res.writeHead(404); res.end('Not found');
    } catch (error) { json(res, { error: error.message }, 500); }
  });
}
function json(res, value, status = 200) { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8' }); res.end(JSON.stringify(value)); }
export { html };
